name: jeda_app
description: "Aplikasi JEDA - Smartphone Addiction Tracker"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  flutter_overlay_window: ^0.5.0
  usage_stats: ^1.0.0
  notification_listener_service: 0.3.5
  permission_handler: ^11.3.1  # downgrade dari 12.0.1
  flutter_local_notifications: ^17.2.4  # ← downgrade dari 19.5.0
  change_app_package_name: ^1.1.0
  installed_apps: ^1.4.0
  path_provider: ^2.1.2
  audioplayers: ^6.0.0
  vibration: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon_jeda.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/model/model_data.json
    - assets/sounds/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300